/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignalerRouteImport } from './routes/signaler'
import { Route as SensibilisationRouteImport } from './routes/sensibilisation'
import { Route as RecompensesRouteImport } from './routes/recompenses'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as GouverneurRouteImport } from './routes/gouverneur'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AutoritesRouteImport } from './routes/autorites'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalerRoute = SignalerRouteImport.update({
  id: '/signaler',
  path: '/signaler',
  getParentRoute: () => rootRouteImport,
} as any)
const SensibilisationRoute = SensibilisationRouteImport.update({
  id: '/sensibilisation',
  path: '/sensibilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensesRoute = RecompensesRouteImport.update({
  id: '/recompenses',
  path: '/recompenses',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const GouverneurRoute = GouverneurRouteImport.update({
  id: '/gouverneur',
  path: '/gouverneur',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoritesRoute = AutoritesRouteImport.update({
  id: '/autorites',
  path: '/autorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/autorites': typeof AutoritesRoute
  '/carte': typeof CarteRoute
  '/gouverneur': typeof GouverneurRoute
  '/interventions': typeof InterventionsRoute
  '/rapports': typeof RapportsRoute
  '/recompenses': typeof RecompensesRoute
  '/sensibilisation': typeof SensibilisationRoute
  '/signaler': typeof SignalerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/autorites': typeof AutoritesRoute
  '/carte': typeof CarteRoute
  '/gouverneur': typeof GouverneurRoute
  '/interventions': typeof InterventionsRoute
  '/rapports': typeof RapportsRoute
  '/recompenses': typeof RecompensesRoute
  '/sensibilisation': typeof SensibilisationRoute
  '/signaler': typeof SignalerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/autorites': typeof AutoritesRoute
  '/carte': typeof CarteRoute
  '/gouverneur': typeof GouverneurRoute
  '/interventions': typeof InterventionsRoute
  '/rapports': typeof RapportsRoute
  '/recompenses': typeof RecompensesRoute
  '/sensibilisation': typeof SensibilisationRoute
  '/signaler': typeof SignalerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/autorites'
    | '/carte'
    | '/gouverneur'
    | '/interventions'
    | '/rapports'
    | '/recompenses'
    | '/sensibilisation'
    | '/signaler'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/autorites'
    | '/carte'
    | '/gouverneur'
    | '/interventions'
    | '/rapports'
    | '/recompenses'
    | '/sensibilisation'
    | '/signaler'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/autorites'
    | '/carte'
    | '/gouverneur'
    | '/interventions'
    | '/rapports'
    | '/recompenses'
    | '/sensibilisation'
    | '/signaler'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AutoritesRoute: typeof AutoritesRoute
  CarteRoute: typeof CarteRoute
  GouverneurRoute: typeof GouverneurRoute
  InterventionsRoute: typeof InterventionsRoute
  RapportsRoute: typeof RapportsRoute
  RecompensesRoute: typeof RecompensesRoute
  SensibilisationRoute: typeof SensibilisationRoute
  SignalerRoute: typeof SignalerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaler': {
      id: '/signaler'
      path: '/signaler'
      fullPath: '/signaler'
      preLoaderRoute: typeof SignalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensibilisation': {
      id: '/sensibilisation'
      path: '/sensibilisation'
      fullPath: '/sensibilisation'
      preLoaderRoute: typeof SensibilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompenses': {
      id: '/recompenses'
      path: '/recompenses'
      fullPath: '/recompenses'
      preLoaderRoute: typeof RecompensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gouverneur': {
      id: '/gouverneur'
      path: '/gouverneur'
      fullPath: '/gouverneur'
      preLoaderRoute: typeof GouverneurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autorites': {
      id: '/autorites'
      path: '/autorites'
      fullPath: '/autorites'
      preLoaderRoute: typeof AutoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AutoritesRoute: AutoritesRoute,
  CarteRoute: CarteRoute,
  GouverneurRoute: GouverneurRoute,
  InterventionsRoute: InterventionsRoute,
  RapportsRoute: RapportsRoute,
  RecompensesRoute: RecompensesRoute,
  SensibilisationRoute: SensibilisationRoute,
  SignalerRoute: SignalerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
